import Head from 'next/head'

export default function Dashboard() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="max-w-5xl mx-auto">
        <section className="flex flex-col gap-1">
          <div className="my-10" />

          <div className="my-4" />
        </section>
      </main>
    </div>
  )
}
