name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    strategy:
      matrix:
        node: ['14.x']
    runs-on: ubuntu-latest

    name: Lint and format
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Cache Yarn dependencies
        uses: actions/cache@v2
        with:
          path: |
            node_modules
          key: ${{ runner.OS }}-${{ matrix.node }}-yarn-cache-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.OS }}-${{ matrix.node }}-yarn-cache-

      - run: yarn --no-progress --non-interactive --frozen-lockfile

      - run: yarn build
      - run: yarn lint
      - run: yarn format

  test:
    strategy:
      matrix:
        node: ['14.x']
    runs-on: ubuntu-latest

    name: Test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Cache Yarn dependencies
        uses: actions/cache@v2
        with:
          path: |
            node_modules
          key: ${{ runner.OS }}-${{ matrix.node }}-yarn-cache-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.OS }}-${{ matrix.node }}-yarn-cache-

      - run: yarn --no-progress --non-interactive --frozen-lockfile

      - run: yarn build
      - run: yarn test
