name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build_and_check:
    strategy:
      matrix:
        node: ['14.x']
    runs-on: ubuntu-latest

    name: Lint and Test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Cache Yarn dependencies
        uses: actions/cache@v2
        with:
          path: |
            node_modules
          key:
            ${{ runner.OS }}-${{ matrix.node }}-yarn-cache-${{
            hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.OS }}-${{ matrix.node }}-yarn-cache-

      - run: yarn --no-progress --non-interactive --frozen-lockfile

      - run: yarn build #next js will lint and typecheck *some* files but to cover everything we run linting and typecheck as separate steps
      - run: yarn lint
      - run: yarn format
      - run: yarn typecheck
      - run: yarn test
      - name: 'Test E2E'
        run: yarn test:e2e
      - name: 'Build storybook'
        run: yarn build-storybook
